// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWD_Project.Data;

#nullable disable

namespace SWD_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318031813_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWD_Project.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenteeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenteeId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "I want to learn MVC",
                            CreatedAt = new DateTime(2026, 3, 18, 10, 18, 13, 255, DateTimeKind.Local).AddTicks(8027),
                            MenteeId = 1,
                            Status = 0,
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Need frontend mentor",
                            CreatedAt = new DateTime(2026, 3, 18, 10, 18, 13, 255, DateTimeKind.Local).AddTicks(8039),
                            MenteeId = 1,
                            Status = 1,
                            Title = "Learn React"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Database optimization",
                            CreatedAt = new DateTime(2026, 3, 18, 10, 18, 13, 255, DateTimeKind.Local).AddTicks(8040),
                            MenteeId = 1,
                            Status = 2,
                            Title = "Learn SQL"
                        });
                });

            modelBuilder.Entity("SWD_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mentee1@gmail.com",
                            FullName = "Nguyen Van A",
                            PasswordHash = "123456",
                            Role = 1,
                            Username = "mentee1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mentor@gmail.com",
                            FullName = "Tran Van B",
                            PasswordHash = "123456",
                            Role = 2,
                            Username = "mentor1"
                        });
                });

            modelBuilder.Entity("SWD_Project.Models.Request", b =>
                {
                    b.HasOne("SWD_Project.Models.User", "Mentee")
                        .WithMany("Requests")
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentee");
                });

            modelBuilder.Entity("SWD_Project.Models.User", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
